# Change these first
owner: yasandev # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: NYC Server
    url: https://www.yasan.dev
    icon: https://yasan.dev/yasan_logo_light_pure.png
  - name: Blog 
    url: https://blog.yasan.dev
    icon: https://yasan.dev/yasan_logo_light_pure.png
  - name: Shop 
    url: https://shop.spreadshirt.com/YASAN
    icon: https://yasan.dev/yasan_logo_light_pure.png

status-website:
  themeUrl: https://status.yasan.dev/yasan-theme.css
  cname: status.yasan.dev
  logoUrl: https://yasan.dev/yasan_logo_light_color_pure.png
  name: YASAN Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# https://upptime.js.org/docs/configuration
