# Change these first
owner: yasandev # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: YASAN.dev
    url: https://www.yasan.dev

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.yasan.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://yasan.dev/yasan_logo_dark_color.svg
  name: YASAN Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
