# Change these first
owner: yasandev # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Toronto Server
    url: https://www.yasan.dev
    icon: https://yasan.dev/yasan_logo_light_pure.png
    assignees:
      - yasandev
  - name: Shop 
    url: https://shop.spreadshirt.com/YASAN
    icon: https://yasan.dev/yasan_logo_light_pure.png
    assignees:
      - yasandev
  - name: Translation Center  
    url: https://translate.yasan.dev
    icon: https://yasan.dev/yasan_logo_light_pure.png
    assignees:
      - yasandev

status-website:
  themeUrl: https://yasan.dev/yasan-theme.css
  cname: status.yasan.dev
  logoUrl: https://yasan.dev/yasan_logo_light_color_pure.png
  name: YASAN Status
  favicon: https://yasan.dev/yasan_logo_light_color_pure.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# https://upptime.js.org/docs/configuration
